wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: false
cell_type:
  value: GRU
dropout:
  value: 0.2
embedding_size:
  value: 384
hidden_size:
  value: 384
learning_rate:
  value: 0.001
num_layers:
  value: 3
