wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: true
cell_type:
  value: RNN
dropout:
  value: 0.2
embedding_size:
  value: 512
hidden_size:
  value: 256
learning_rate:
  value: 0.001
num_layers:
  value: 3
