wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: false
cell_type:
  value: GRU
dropout:
  value: 0.3
embedding_size:
  value: 384
hidden_size:
  value: 384
learning_rate:
  value: 0.1
num_layers:
  value: 1
