wandb_version: 1

batch_size:
  value: 64
bidirectional:
  value: true
cell_type:
  value: LSTM
dropout:
  value: 0.4
embedding_size:
  value: 512
hidden_size:
  value: 256
learning_rate:
  value: 0.01
num_layers:
  value: 2
