wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: false
cell_type:
  value: GRU
dropout:
  value: 0.2
embedding_size:
  value: 128
hidden_size:
  value: 256
learning_rate:
  value: 0.1
num_layers:
  value: 3
