wandb_version: 1

batch_size:
  value: 64
bidirectional:
  value: true
cell_type:
  value: RNN
dropout:
  value: 0.4
embedding_size:
  value: 128
hidden_size:
  value: 512
learning_rate:
  value: 0.001
num_layers:
  value: 2
