wandb_version: 1

batch_size:
  value: 128
bidirectional:
  value: false
cell_type:
  value: LSTM
dropout:
  value: 0.3
embedding_size:
  value: 256
hidden_size:
  value: 256
learning_rate:
  value: 0.001
num_layers:
  value: 1
