wandb_version: 1

batch_size:
  value: 64
bidirectional:
  value: true
cell_type:
  value: GRU
dec_dropout:
  value: 0.4
embedding_size:
  value: 512
enc_dropout:
  value: 0.2
hidden_size:
  value: 256
learning_rate:
  value: 0.01
num_epochs:
  value: 20
num_layers:
  value: 1
