wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.11.2
    start_time: 1684210767.876744
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.2
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 64
bidirectional:
  desc: null
  value: true
cell_type:
  desc: null
  value: RNN
dropout:
  desc: null
  value: 0.4
embedding_size:
  desc: null
  value: 128
hidden_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.001
num_layers:
  desc: null
  value: 2
