wandb_version: 1

batch_size:
  value: 128
bidirectional:
  value: true
cell_type:
  value: GRU
dropout:
  value: 0.4
embedding_size:
  value: 384
hidden_size:
  value: 512
learning_rate:
  value: 0.1
num_layers:
  value: 3
