wandb_version: 1

batch_size:
  value: 32
bidirectional:
  value: true
cell_type:
  value: LSTM
dropout:
  value: 0.2
embedding_size:
  value: 256
hidden_size:
  value: 384
learning_rate:
  value: 0.1
num_layers:
  value: 1
