wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.11.2
    start_time: 1684211027.452552
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.2
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 32
bidirectional:
  desc: null
  value: false
cell_type:
  desc: null
  value: GRU
dropout:
  desc: null
  value: 0.3
embedding_size:
  desc: null
  value: 384
hidden_size:
  desc: null
  value: 384
learning_rate:
  desc: null
  value: 0.1
num_layers:
  desc: null
  value: 1
